---
title: "R Introduksjon_130921"
output: html_notebook
---

```{r}
2+2
x <- 2+2
x
(y <- 3+3)
(z = 4)
(z = z + 2)
rm(z)
x + y
x - y
x * y
x / y
x^y
```

## Combine

```{r}
x <- c(2, 7, 9, 13)
y <- c(6, 2)
z <- x + y
y <- c(y, 3)
(z <- x + y)
```

## Typer av vektorer

```{r}
class(x)
typeof(x)
x <- 2L
class(x)
typeof(x)
x <- 2.
class(x)
typeof(x)
x <- 2L
y <- 4.1
typeof(x)
typeof(y)
z <- c(x,y)
typeof(z)
z <- c(x, y, "s")
typeof(z)
z[1]
z[2]
x + y 
t <- x + y
typeof(t)
# eksempel på feil: z[1] + z[2]
```

R jobber med vektorer. Alle element må være av samme type. R konverterer
automatisk til en mer generell type.

```{r}
l <- list(x = 1:4, y = c(TRUE, FALSE, FALSE), z = c("aa", "ba"), zz = c(2.1, 4.33))
str(l)
```

```{r}
l[1]
l[2]
l[3]
l[4]
l[c(2, 4)]
l[[2]]
```

## Dataframes

Viktigste strukturen i R. Dataframes er en nær slektning i tidyverse som
hete tibble. En tibble/dataframe er en liste av vektorer med **samme
lengde**

```{r}
df1 <- data.frame(x = 1:1000, y = rnorm(1000))
df1_as_tib <- tibble(df1)
#Prefer tibble
tib1 <- tibble(x = 1:1000, y = rnorm(1000), z = rep(c("aa", "bb"), 500))
tib1
View(tib1)
```


## Help
Se help nede i høyre hjørne.
```{r}
?ls
```



```{r}
# siste
```



## Plukke tilfeldig fra tibble
```{r}
tib1[, 2]
tib1[, 1]
tib1[, c(1, 3)]
tib1_5 <- tib1[c(5, 77, 123, 671, 923), ]
tib1_5
tib1[sample(x = 1000, size = 10), ]
```





